name: Bug Report
description: You found a bug? - Create an issue!
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Co sie stało?
      description: Co powinno się wydarzyć, a co stało się innego? 
      placeholder: Rzucenie kostką crashuje grę.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Jak do tego doszło?
      description: | 
        Opisz, jak deweloperzy mogą spowodować wystąpienie błędu - gdzie kliknąć, jaką opcję itd. Jest to zdecydowanie najważniejsza część raportu - często jest bardzo trudne lub nawet niemożliwe zdiagnozowanie problemu, jeśli nie znamy warunków, w których się pojawia. Można dorzucić screenshota.
      placeholder: |
        1. Uruchom singleplayer na opcjach default.
        2. Rzuć kostką.
        3. Gra się crashuje.
    validations:
      required: true
  - type: dropdown
    id: gamemode
    attributes:
      label: Tryb gry
      description: Na jakim trybie gry występuje błąd?
      options:
        - Żadnym
        - Lokalnym
        - Online
        - Lokalnym i online
    validations:
      required: true
  - type: dropdown
    id: prevalence
    attributes:
      label: Częstotliwość
      description: Jak często pojawia się problem?
      options:
        - Raz
        - Czasami
        - Zawsze
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Wersja
      description: Jaka to wersja gry?
      options:     
        - 0.1.0-beta.1
        - Inna
    validations:
      required: true
  - type: input
    id: otherversion
    attributes:
      label: "-"
      description: Jeśli wybrałeś wersję gry "Inna" - podaj id ostatniego commita.
  - type: dropdown
    id: operating-systems
    attributes:
      label: System operacyjny
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true