# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore WindowsWZIMopoly.sln
    - name: Build debug
      run: dotnet build --configuration Debug --no-restore WindowsWZIMopoly.csproj
      working-directory: WZIMopoly
    - name: Unit tests
      run: dotnet test --no-restore --verbosity normal TestWZIMopoly.csproj
      working-directory: TestWZIMopoly

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore LinuxWZIMopoly.sln
    - name: Build debug
      run: dotnet build --configuration Debug --no-restore LinuxWZIMopoly.csproj
      working-directory: WZIMopoly
    - name: Unit tests
      run: dotnet test --no-restore --verbosity normal TestWZIMopoly.csproj
      working-directory: TestWZIMopoly